apiVersion: apps/v1
kind: deployment
metadata:
  name: app1
  labels:
  app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata: 
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: 
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: app1
spec:
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080


